### PR TITLE
add CI

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 66e7897 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 66e7897 with merge 66e7897...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/cortex-m-hal/builds/241354603?utm_source=github_status&utm_medium=notification)
Approved by: japaric
Pushing 66e7897df90f60f7440131b30cf89e5b5c929146 to master...

**Pull request merged**
